name: html

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@v0.4.4
        with:
          root: index.html